### ISSUE TITLE
Eleccion del lenguaje de programación

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#10]
Hola @moshidev se me ha asignado este repositorio para realizar el objetivo 2.

El primer paso es buscar y discutir que lenguaje de programación se va a utilizar para realizar el proyecto, de forma que te propongo el uso de `TypeSript` o `Go`, ambos se pueden ajustar bien al tipo de problema que planteas. 

A modo de consejo escogería aquél con el que te sientas más cómodo, sin olvidar que el aprender un lenguaje puede ser una herramienta muy útil para un futuro.

Coméntame cualquier otro lenguaje que hayas pensado siempre que lo hubiese recomendado el profesor para no complicarlo demasiado :sweat_smile:

**Comment by moshidev** [comment]
¿Qué criterios has tenido más en cuenta? Se me olvidó comentarlo, pero cada máquina genera alrededor de 500 reportes de sensores al día, y se estima que cada cliente puede llegar a tener 50 o 100 máquinas conectadas a Internet. 

Sobre los lenguajes (cuento mi experiencia con los lenguajes, aunque suene contundente si me equivoco en algo o crees que los beneficios que no menciono superan a las cosas negativas no te cortes)

No tengo experiencia con Go (aunque me gustaría, Plan9 me tuvo interés en su día). He intentado buscar alguna herramienta para manejar tantos datos y generar estadísticas y no he encontrado mucho, no sé si es el más adecuado.

Typescript preferiría que no. Es ineficiente computacionalmente y, por experiencia con JavaScript, una fuente enorme de bugs tontísimos que cualquier compilador te advertiría. Además, no sé su capacidad para procesar los datos.

Creo que a lo mejor Python (muy a mi pesar), Julia, R, Rust o C++ podrían ser mejores alternativas.

Python/Julia/R porque tienen muchas herramientas para estadística compiladas (aunque sean lenguajes ineficientes computacionalmente al menos el tratamiento de los datos no lo es).

Rust por su rendimiento computacional, ayuda a la correctitud y preferencia personal.

C++ porque tiene bastante soporte y lo conoce bastante gente.

**Comment by josemponce** [comment]
Bueno yo me estuve basando en las recomendaciones del profesor y un poco en mi experiencia, por eso principalmente te mencione TypeScript y Go.

Aun así comprendo tus motivos, así que te propongo que si realmente estás cómodo con `R`, te animaras con este lenguaje por las posibilidades que te ofrece. 

De todos modos como tiene que ser una decisión tuya según tus preferencias también te recomendaría `Rust` que al ser un lenguaje tipado puede ayudarte y por su rendimiento. O `Go` que tiene un fuerte parecido con `C++` del que mencionas que podría ser una buena alternativa.

Espero tu elección, un saludo. :wave:

**Comment by moshidev** [comment]
Bueno a ver, es algo a ver entre los dos jaja. La cosa es buscar lo mejor para el proyecto y para ambos. Perdona por haber tardado en responder, estoy haciendo horas extra en el trabajo.

He estado viendo Julia, principalmente porque me lo han recomendado. A diferencia de Rust o Go tiene herramientas para estadística, machine learning, etc. A diferencia de Python parece ser que es eficiente computacionalmente al nivel de Java o así (al menos en términos muy generales). A diferencia de R es un lenguaje de propósito general.

Por otra parte Julia utiliza tipado dinámico, tiene menos bibliotecas para python (que para el caso no sé si llega a ser relevante), es un proyecto incluso más reciente que Rust y seguramente tenga muchos más contras.

**Comment by josemponce** [comment]
De acuerdo, pues si te parece bien nos quedamos con Julia :+1:

**Comment by moshidev** [comment]
okay, cierra este issue cuando hagas el commit
