### ISSUE TITLE
Propuesta de estructura del problema

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#12]
Hola @moshidev, tras estar pensandolo te propongo que sigamos la siguiente estructura compuesta por dos entidades en las que dentro podemos encontrar varios objeto-valor.

## Máquina

Esta entidad estaría relacionada con los issue #8 y #9. Debemos de poder guardar la información que nos reporten los sensores para poder estimar el estado de la máquina así como detectar fallos en el sistema. Para esto último debemos reinterpretar los datos que tenemos.

Espero tu opinión al respecto y voy lo detallando en los siguientes issues.

**Comment by moshidev** [comment]
Yo me centraría sólo en el diagnóstico, lo del milestone 0, y así no se te complica el problema. En plan, como si el sistema sólo pudiese funcionar para una máquina, y sólo pudiese, dado un histórico , dar un diagnóstico.
> definimos en el lenguaje de programación escogido las estructuras de datos
necesarias para poder aplicar un algoritmo cualquiera que nos permita conocer
si una máquina está funcionando de forma incorrecta.

**Comment by josemponce** [comment]
He actualizado la propuesta @moshidev, creo que ya está mejor.
