### ISSUE TITLE
¿Qué características tiene una máquina?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#13]
Relacionado con el issue #12, definimos la entidad máquina de forma que ¿Qué caracterísiticas debe tener una máquina?

Propongo la siguiente estructura:

- El conjunto de datos en tiempo real.
- El estado actual.
- Los problemas detectados.
- Operaciones sobre los datos de reportes.

**Comment by moshidev** [comment]
Creo que aquí se mezclan muchos conceptos. Yo lo vería más como: meto unos datos (histórico), con una estructura en concreto, obtengo obtengo otros datos (el estado actual y los problemas detectados). El milestone 0 sólo busca dar un diagnóstico dado un histórico.

**Comment by josemponce** [comment]
Si creo que sería mejor. He actualizado la estructura.

**Comment by moshidev** [comment]
¿Cómo la has actualizado? No veo diferencias.

Por otra parte, ¿realmente queremos modelar una máquina? Lo único que queremos hacer es, dado un histórico, obtener un diagnóstico. ¿Para conocer el estado de la máquina necesito tener en memoria todo el histórico?

**Comment by josemponce** [comment]
No haría falta, podríamos guardar únicamente los últimos reportes, de manera que no haría falta hacer uso de mucha memoria

**Comment by moshidev** [comment]
¿Cuándo sabemos qué reportes son interesantes o cuales no? Lo decía más en el sentido de que un histórico (que no la potencial referencia a un histórico) es algo completamente independiente a un diagnóstico. Son dos responsabilidades / datos diferentes, aunque guarden algo de relación.
