### ISSUE TITLE
¿Qué características tiene un propietario?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#14]
En relación con el issue #12, debemos definir que características tiene un propietario de forma que yo propongo la siguiente:

- Los datos de cualquier persona.
- El listado de máquinas que tiene.

Considero el propietario una entidad ya que sus valores no serán inmutables ya que las máquinas que tenga podrán ir variando a lo largo del tiempo.

**Comment by moshidev** [comment]
Entiendo que las personas en sí no son relevantes para el análisis y diagnóstico de una máquina. En plan, el milestone 0 se restringe únicamente a la parte de diagnóstico

> definimos en el lenguaje de programación escogido las estructuras de datos
necesarias para poder aplicar un algoritmo cualquiera que nos permita conocer
si una máquina está funcionando de forma incorrecta.

**Comment by josemponce** [comment]
Si, creo que no sería necesario para que fuera minimamente viable el producto que pretendemos hacer.

**Comment by josemponce** [comment]
Hola @moshidev, finalmente he eliniminado este struct asi que podríamos etiquetar este issue como invalid-issue.
