### ISSUE TITLE
¿Cómo representamos los datos de los reportes de una máquina?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#15]
En relación al issue #13, debemos describir la representación de los datos en tiempo real de una máquina.

Basandonos en el archivo de [funcionamiento de una maquina](https://github.com/moshidev/MaquiTracker/blob/main/docs/funcionamiento_maquina.md) y el issue #9 podemos identificar primeramente 6 sensores por máquina (usos, tiempo en funcionamiento, aceite, presión, EVs y antigüedad) que combinado con la infomración que obtuve en el issue #10 donde se indica que cada máquina ofrece alrededor de 500 reportes al día nos hace indicar el uso de una estructura eficiente pero al mismo tiempo cómoda de usar por lo que planteo una matriz de datos Float.

Por un lado las filas podrán representar los sensores, a priori 6, y las columnas cada reporte hecho en cada momento del día.

**Comment by moshidev** [comment]
No sé cómo va a ser en el lenguaje mejor. Lo cierto es que aunque tenemos esos 6 sensores, genuinamente no se si aglutinarlos va a ser mejor o peor. Por ejemplo, las EVs tienen relación con la temperatura, pero no tanto con el número de árboles vibrados. Tendría que ser una estructura que al final vaya a ser lo suficientemente eficiente e idiomatica

**Comment by josemponce** [comment]
Si quieres empezamos usando esta estructura y luego se va mejorando en lo que podamos.

**Comment by moshidev** [comment]
Tal vez, o tal vez a lo mejor no nos interesa tener en memoria de forma
permanente esos datos, sino los datos que extraemos de estos. Por otra
parte, más que la representación de los datos, creo que es más importante
la interfaz de la Estructura de Datos. Sea como fuere no me hagas mucho
caso que estoy que me caigo. nini

**Comment by josemponce** [comment]
Abro un nuevo issue para discutir este tema.
