### ISSUE TITLE
¿Cúanta precisión necesitamos tener en los datos de la matriz en tiempo real?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#16]
En relación al issue #15, mencionamos que creamos una matriz de datos Float, pero falta decidir que dato en concreto se usará.

En principio resultaría más eficiente el uso de un tipo de dato como `int`, pero doy por hecho que muchos de los reportes de los sensores serán con decimales lo que nos obliga a usar un tipo `Float` para este caso.

Ahora nos encontramos con `Float32` y `Float64`, el primero tiene menos precisión que el segundo ya que solo se guardan 4 bytes para almacenar los números respecto a los 8 bytes que usa el segundo. Por lo que habría que discutir que precisión necesitamos tener en nuestro problema y si esta precisión esta justificada ante el empeoramiento del rendimiento que obtendremos.

**Comment by moshidev** [comment]
Float32 va perfe, si luego necesitamos más o menos optimizamos

**Comment by josemponce** [comment]
perfecto :+1:
