### ISSUE TITLE
¿Cómo representamos el estado actual de una máquina?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#17]
En relación al issue #13 debemos decidir como representaremos el estado de una máquina. Basándome en el issue #9, se define el estado de una máquina como el número de días restantes para que esta de algún tipo de fallo, por lo tanto podríamos representarlo como un dato de tipo `Int` que nos indicara dicho número de días.

**Comment by moshidev** [comment]
Sí, sería una de las historias, número de días restantes. Con un int creo que también iría bien. Tal vez junto a un float para representar un grado de certeza?

**Comment by josemponce** [comment]
Dependería de cuanto complicado quisieras realizar el programa, porque lo vería algo quizás complicado de obtener. 

Por un lado estaría estrechamente relacionado con cómo de bien estubiera implementado el algoritmo que calculara la estimación de días restantes pero, por otro lado si usamos distintos tipos de maquinaria podría ser más útil ya que no todas tienen la misma resistencia, aunque este último dato sería algo complicado de obtener. Yo lo enfocaría más a cómo el propietario cuida sus herramientas, si es más bruto o por el contrario realiza un mantenimiento diario.

En tal caso podríamos por lo tanto usar un struct de la siguiente forma `( Int , Float32 ) `.

**Comment by moshidev** [comment]
¿Por qué es mutable? Por otra parte, cuando Peluso quiere obtener un reporte, ¿vamos a mantener TODOS los reportes en memoria? no vamos a tener memoria

**Comment by josemponce** [comment]
El estado de la máquina puede cambiar con cada reporte que recibamos, es necesario por lo tanto que sea mutable.

**Comment by moshidev** [comment]
Pero vuelvo a lo mismo, no pone en ninguna parte que sea necesario hacerlo en tiempo real. Va a complicar la implementación, y va a ser más difícil encontrar una interfaz que no mezcle conceptos. Optimizar en este sentido creo nos va a alejar de hacer un modelo que realmente sea válido.

**Comment by josemponce** [comment]
Se podría calcular cada X tiempo de forma que nos proporcionase la suficiente información útil como al mismo tiempo no complicar la implementación.

**Comment by moshidev** [comment]
¿Cómo podría ayudar calcularlo cada x tiempo a encontrar el modelo?

**Comment by josemponce** [comment]
No se si puede haber sido una confusión, pero cuando escribí calcularlo en tiempo real, me refería a calcularlo cada vez que recibamos un reporte de la máquina. ¿Es ese el problema que planteas o te refieres a otra cosa?

En caso de que sea eso creo que sería oportuno cambiar el nombre de Datos En Tiempo Real a Reporte Sensores para no llegar a ninguna confusión.
