### ISSUE TITLE
¿Cómo representamos el fallo de una máquina?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#18]
En relación con el issue #13, debemos decidir cual será el tipo de dato para representar los fallos que puede tener una máquina.

Como se explica en la historia de usuario #8 se conocen de ante mano ciertos problemas que pueden ocurrir, de manera que se le puede asignar a cada uno un código con un tipo de dato `Int`.

**Comment by moshidev** [comment]
Mejor con un enumerado en todo caso. De todas formas incluso con un string creo que iría bien

**Comment by josemponce** [comment]
Sí, me parace bien. 
Yo proponía el `Int` a modo de que era lo minimamente viable para poder representar un problema de la máquina.

**Comment by moshidev** [comment]
¿Entonces, mientras hagamos debug o cuando hagamos una interfaz, tendremos que irnos a una documentación (potencialmente desactualizada) para manualmente recuperar la equivalencia entre entero y tipo de fallo?

**Comment by josemponce** [comment]
En el código lo he creado como un `String`, que creo que fue lo que decidimos.

**Comment by moshidev** [comment]
Leí mal!
