### ISSUE TITLE
¿Qué operaciones necesitamos para poder estimar los fallos de la máquina?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#19]
Nos centraremos en resolver los problemas del issue #8.

En relación al issue #13, por un lado se plantean tres situaciones en las que se detectaría un fallo en la máquina, por lo que propondría tres operaciones para resolver respectivamente estas situaciones.
- `la temperatura del aceite del circuito es distinta a la típica:` calcular una media de las últimas mediciones de la temperatura del aceite para detectar cuando es distinta a la normal.
- `la presión del circuito es distinta a la típica:` del mismo modo se podría calcular la media de x mediciones más recientes de la presión del circuito para detectar cuando es distinta a la normal.
- `una electroválvula empieza paulativamente a consumir más corriente que de costumbre:` se resolvería de la misma forma con la diferencia de que quizás habría que tener en cuenta más registros que respecto a los casos anteriores.

**Comment by moshidev** [comment]
Tienes más información [en este documento](https://github.com/moshidev/MaquiTracker/blob/main/docs/funcionamiento_maquina.md)
