### ISSUE TITLE
¿Cómo podemos realizar el mantenimiento preventivo?

### ISSUE THREAD

**Issue by josemponce** [moshidev/MaquiTracker#21]
En relación con el issue #9 y el #17, necesitamos poder saber cuantos días faltan para que falle la máquina y para ello tenemos 6 sensores. Tres de ellos están bastante relacionados (el número de árboles vibrados, el número de horas de trabajo en las que se han estado vibrando árboles y la antiguedad de la máquina) que podrían usarse directamente en el algoritmo para calcular el estado. 
Por otro lado están los sensores de temperatura del aceite del circuito, presión del circuito y corriente consumida por cada electroválvula en los que sería útil realizar alguna transformación antes de pasárselos al algoritmo.

**Comment by moshidev** [comment]
En [este documento](https://github.com/moshidev/MaquiTracker/blob/main/docs/funcionamiento_maquina.md) tienes más información. Puedes empezar centrándote en un caso de diagnóstico en concreto, ver qué haría falta para realizarlo, y empezar a iterar a partir de ahí.

**Comment by josemponce** [comment]
Realmente no es un problema muy complejo donde haya que utilizar herramientas más avanzadas que una simple media para comprobar la variación de los últimos reportes respecto a una referencia para saber si la temperatura del aceite está aumentando por ejemplo (los otros casos son muy parecidos, aumento de la presión o aumento del consumo).  
Aunque es cierto que se podría añadir funciones que analizaran las series temporales en cada uno de los datos de forma que podamos predecir en que momentos puede fallar la máquina. En este caso Julia cuenta con bibliotecas que pueden hacer este trabajo por nosotros como pueden ser `TimeSeries`, `StatsBase` o `StatsModels`, en las que se realiza la división entre tendencias, estacionalidad y residuos que son necesarios para calcular la estimación.

**Comment by josemponce** [comment]
Otro aspecto que se podría considerar quizás sería la correlación que pudieran tener las distintas series entre sí, pero esto viene en principio definido en el [documento](https://github.com/moshidev/MaquiTracker/blob/main/docs/funcionamiento_maquina.md) por lo que no haría falta calcularlo y sería en la implementación del algoritmo donde cobraría más importancia.

**Comment by josemponce** [comment]
Hola @moshidev, tras la reunión que hemos hecho, he estado investigando un poco más sobre lo que proponías.
En el [documento](https://github.com/moshidev/MaquiTracker/blob/main/docs/funcionamiento_maquina.md) donde se explica el funcionamiento de las máquinas se extrae que puede fallar cuando sobrepasa cierto límite o mínimo. Al mismo tiempo tenemos unas series de datos (aceite, presión y consumo) que describen funciones a lo largo del tiempo, por lo que una posible solución sería el uso de interpolación para averiguar la tendencia de estas funciones que he mencionado de forma que podamos estimar el punto de la intersección entre esta y el límite por ejemplo de forma que podamos predecir cuantos días quedan para que se llegue a tal punto.

Para obtener esta interpolación Julia tiene el paquete de Interpolations.jl que implementa una variedad de funciones de interpolación para Julia. Puedes obtener más información [aqui](http://juliamath.github.io/Interpolations.jl/latest/). 

En concreto podría usarse la funcion: `interpolate(y, x)`, en nuestro caso `y` sería el valor del tiempo y `x` el valor de la temperatura( presión o consumo) en cada reporte.

**Comment by josemponce** [comment]
De forma que los datos que pasaríamos a ese hipotético algoritmo que calculara el estado de la máquina serían por un lado las funciones calculadas por interpolación de las series de aceite, presión y consumo, y por otro lado el número de árboles vibrados, el número de horas de trabajo en las que se han estado vibrando árboles y la antiguedad de la máquina.

Espero tu opinión, un saludo. :wave:

**Comment by moshidev** [comment]
> De forma que los datos que pasaríamos a ese hipotético algoritmo que calculara el estado de la máquina serían por un lado las funciones calculadas por interpolación de las series de aceite, presión y consumo, y por otro lado el número de árboles vibrados, el número de horas de trabajo en las que se han estado vibrando árboles y la antiguedad de la máquina.

¿No se mezclarían muchas cosas? ¿Qué te parece centrarnos únicamente en un caso a predecir? (por ejemplo, en el de las electroválvulas)

**Comment by moshidev** [comment]
Intenta hacerlo de esta forma:
1. Decide exactamente qué queremos resolver (hay muchas condiciones y 2 HUs diferentes, un PMV no contemplará todos los casos ni todas las HUs, empezamos por uno sólo)
2. Deduce qué componentes son necesarios (no tienen por qué venir explicitados en las HUs, probablemente serán consecuentes, probablemente la HU expresa las cosas de una forma amigable para un humano y no para una máquina). 
3. Una vez identificado _y entendido_ el problema a resolver busca una interfaz para el servicio.
4. Una vez sabes las dependencias de datos del servicio, y lo que tiene que devolver, imagínate implementando ese problema.
5. Implementa en el lenguaje siguiendo tu mejor criterio (no hace falta que me preguntes sobre tipos, interfaces, etc).

Si te quedas atascado en uno de los pasos pregúntame, pregunta a chatGPT o pregunta a Google, según creas que sea mejor.

**Comment by josemponce** [comment]
Esta bien, comenzaremos por las electrovávulas en un nuevo issue.
